pipeline {
    agent any
    stages {
        stage('SCM checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/BambooThink/BootcampDevOps2023'
            }
        }
    }
}