pipeline {
    agent any
    stages {
        stage('SCM checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/BambooThink/BootcampDevOps2023'
            }
        }
        stage('Show a message') {
            steps {
                echo 'We are in the stage of showing a message'
            }
        }
        stage('Ansible Test') {
            steps{
                sh 'ansible-playbook --check -i Ejercicios/Ansible/Jenkins-Installation/inventory.ini Ejercicios/Ansible/Jenkins-Installation/playbook.yml'
            }
        }
    }
}